#!/usr/bin/env perl
use Flexconf::Cli;
Flexconf::Cli::main @ARGV;

__END__


=head1 NAME

Flexconf command line interface implementation

=head1 SYNOPSIS

    flx [ -t -c -f -g -q ]
      [-t type]              # file type
      [-c path-to-conf]      # conf path to open
      [-f 'flexconf script'] # flex script to execute
      [-g flex.path]         # get value in json
      [-q flex.path]         # get scalar value in plain

=cut

